apiVersion: v1
kind: Pod
metadata:
  name: simple-echo
spec:
  containers:
    - name: nginx
      image: nginx
      env:
        - name: BACKEND_HOST
          value: localhost:8080
      ports:
        - containerPort: 80
    - name: echo
      image: marmindev/golang:1
      ports:
        - containerPort: 8080
